[package]
authors = ["Patrick Fernie <patrick.fernie@gmail.com>"]
description = "Implementation of Cookie storage and retrieval"
name = "cookie_store"
version = "0.14.0"
edition = "2018"
repository = "https://github.com/pfernie/cookie_store"
documentation = "https://docs.rs/cookie_store"
readme = "README.md"
license = "MIT/Apache-2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["reqwest_impl"]

# uses `indexmap::IndexMap` in lieu of HashMap internally, so cookies are maintained in insertion/creation order
preserve_order = ["indexmap"]
# provide an implementation of `reqwest::cookie::CookieStorage`
reqwest_impl = ["reqwest", "bytes"]

[dependencies]
idna = "0.2.0"
log = "0.4.8"
psl-types = "2.0.2"
serde = { version = "1.0.111", features = [ "derive" ] }
serde_json = "1.0.55"
time = "0.2.16"
url = "2.1.1"

indexmap = { version = "1.4.0", optional = true }
reqwest = { version = "^0.11.2", optional = true, features = ["cookies"] }
bytes = { version = "1", optional = true }

[dependencies.cookie]
features = ["percent-encode"]
version = "0.15.0"

[dev-dependencies]
env_logger = "0.8.3"
pretty_assertions = "0.7.1"
psl = "2.0.6"
tokio-test = "^0.4.1"
